FROM node:18-alpine

# Ensure all packages installed
ENV NODE_ENV development

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY ["package.json", "pnpm-lock.yaml*", "./"]

RUN pnpm install

COPY . .

# NOTE: We DO NOT copy the rest of the source code.
# The source code will be mounted as a volume from your local machine.
# This is what enables hot-reloading.

EXPOSE 3000
EXPOSE 24678

CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]
